name: multiply-prior-engine

channels:
  - conda-forge
dependencies:
  - python>=3.8
  - gdal=2.4
  - libgdal
  - gcc=12.1.0
  - cxx-compiler
  - libgcc
  - libstdcxx-ng
  - lazrs-python
  - numpy
  - shapely
  - h5py
  - pandas
  - scipy
  - setuptools
  - matplotlib
  - pytest
  - netCDF4
  - PyYAML
  - typing
  - python-dateutil
  - m2r
  - recommonmark
  - sphinx_rtd_theme
  - pip
  - pip:

